spring.application.name=lms

spring.datasource.url=jdbc:postgresql://your_database_host:5432/your_database_name
spring.datasource.username=your_database_username
spring.datasource.password=your_database_password

jwt.secret=your_jwt_secret
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Base URL
app.base-url=http://localhost:8080

# Email sending related
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@example.com
spring.mail.password=your_email_app_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Sender
mail.from=${spring.mail.username}

############################################