spring.application.name=lms

spring.datasource.url=jdbc:postgresql://localhost:5432/lms
spring.datasource.username=DB_USERNAME
spring.datasource.password=DB_PASSWORD

jwt.secret=JWT_SECRET
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Base URL
app.base-url=http://localhost:8080

# Email sending related

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=EMAIL_USERNAME
spring.mail.password=EMAIL_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Sender
mail.from=${spring.mail.username}

############################################